import { drizzle } from "drizzle-orm/mysql2";
import mysql from "mysql2/promise";
import dotenv from "dotenv";
dotenv.config();

const connection = await mysql.createConnection(process.env.DATABASE_URL);
const db = drizzle(connection);

const brokers = [
  // ─── CRITICAL TIER (💐) ───────────────────────────────────────────────────
  { name: "BeenVerified", domain: "beenverified.com", searchUrl: "https://www.beenverified.com/people/", optOutUrl: "https://www.beenverified.com/app/optout/search", removalMethod: "form", priorityTier: "critical", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","email","relatives","criminal"]), parentCompany: "Intelius", subsidiaries: JSON.stringify(["PeopleLooker","PeopleSmart"]), notes: "One opt-out per email address. Confirm via email link." },
  { name: "CheckPeople", domain: "checkpeople.com", searchUrl: "https://checkpeople.com/", optOutUrl: "https://checkpeople.com/opt-out", removalMethod: "form", priorityTier: "critical", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","age","relatives"]), notes: "Requires birthdate and full legal name." },
  { name: "ClustrMaps", domain: "clustrmaps.com", searchUrl: "https://clustrmaps.com/person/", optOutUrl: "https://clustrmaps.com/bl/opt-out", removalMethod: "form", priorityTier: "critical", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","email"]) },
  { name: "Intelius", domain: "intelius.com", searchUrl: "https://www.intelius.com/people-search/", optOutUrl: "https://www.intelius.com/opt-out/", removalMethod: "email", removalEmail: "support@mailer.intelius.com", priorityTier: "critical", difficultyRating: "medium", requiresId: false, requiresPhone: true, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","email","criminal","relatives"]), subsidiaries: JSON.stringify(["Addresses.com","Anywho","Classmates","InstantCheckmate","TruthFinder","USSearch","Zabasearch","PeopleFinder","PeopleLookup"]), notes: "Also call 1-888-245-1655. Owns many subsidiary sites." },
  { name: "MyLife", domain: "mylife.com", searchUrl: "https://www.mylife.com/", optOutUrl: "https://www.mylife.com/ccpa/index.pubview", removalMethod: "email", removalEmail: "privacy@mylife.com", priorityTier: "critical", difficultyRating: "hard", requiresId: false, requiresPhone: true, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","email","reputation","relatives","criminal"]), notes: "Call (888) 704-1900. Also try removalrequests@mylife.com." },
  { name: "Nuwber", domain: "nuwber.com", searchUrl: "https://nuwber.com/", optOutUrl: "https://nuwber.com/removal/link", removalMethod: "form", priorityTier: "critical", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","email","age","relatives"]), removalEmail: "support@nuwber.com" },
  { name: "PublicDataUSA", domain: "publicdatausa.com", searchUrl: "https://publicdatausa.com/", optOutUrl: "https://publicdatausa.com/remove.php", removalMethod: "form", priorityTier: "critical", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","vehicles","political"]), notes: "Requires email from recognized provider (Gmail/Outlook/Yahoo)." },
  { name: "Radaris", domain: "radaris.com", searchUrl: "https://radaris.com/", optOutUrl: "https://radaris.com/page/how-to-remove", removalMethod: "form", removalEmail: "customer-service@radaris.com", priorityTier: "critical", difficultyRating: "hard", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","email","criminal","social"]), notes: "May need to email if form fails. Respond to auto-reply." },
  { name: "SmartBackgroundChecks", domain: "smartbackgroundchecks.com", searchUrl: "https://www.smartbackgroundchecks.com/", optOutUrl: "https://www.smartbackgroundchecks.com/optout", removalMethod: "form", priorityTier: "critical", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","criminal","relatives"]), notes: "Also removes from PeopleFinders." },
  { name: "Spokeo", domain: "spokeo.com", searchUrl: "https://www.spokeo.com/", optOutUrl: "https://www.spokeo.com/optout", removalMethod: "form", priorityTier: "critical", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: true, dataTypes: JSON.stringify(["name","address","phone","email","social","relatives"]), notes: "Confirm via email. Paid accounts may still show data." },
  { name: "That's Them", domain: "thatsthem.com", searchUrl: "https://thatsthem.com/", optOutUrl: "https://thatsthem.com/optout", removalMethod: "form", priorityTier: "critical", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","email","ip"]) },
  { name: "WhitePages", domain: "whitepages.com", searchUrl: "https://www.whitepages.com/", optOutUrl: "https://www.whitepages.com/suppression-requests", removalMethod: "phone", priorityTier: "critical", difficultyRating: "hard", requiresId: false, requiresPhone: true, requiresPayment: true, dataTypes: JSON.stringify(["name","address","phone","relatives"]), subsidiaries: JSON.stringify(["411.com"]), notes: "Requires phone verification. Also check WhitePages Premium." },

  // ─── HIGH TIER (☠) ────────────────────────────────────────────────────────
  { name: "Acxiom", domain: "acxiom.com", searchUrl: "https://isapps.acxiom.com/optout/optout.aspx", optOutUrl: "https://isapps.acxiom.com/optout/optout.aspx", removalMethod: "form", priorityTier: "high", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","demographics","purchase","financial"]), notes: "Call (877) 774-2094 if no email. International portal available." },
  { name: "Advanced Background Checks", domain: "advancedbackgroundchecks.com", searchUrl: "https://www.advancedbackgroundchecks.com/", optOutUrl: "https://www.advancedbackgroundchecks.com/removal", removalMethod: "form", priorityTier: "high", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","criminal","relatives"]) },
  { name: "Ancestry.com", domain: "ancestry.com", searchUrl: "https://www.ancestry.com/", optOutUrl: "https://www.ancestry.com/cs/legal/privacycenter", removalMethod: "email", removalEmail: "privacy@ancestry.com", priorityTier: "high", difficultyRating: "hard", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","historical","family"]), notes: "Requires free account. Email profile URLs." },
  { name: "FamilyTreeNow", domain: "familytreenow.com", searchUrl: "https://www.familytreenow.com/", optOutUrl: "https://www.familytreenow.com/optout", removalMethod: "form", priorityTier: "high", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","relatives","age"]) },
  { name: "FastPeopleSearch", domain: "fastpeoplesearch.com", searchUrl: "https://www.fastpeoplesearch.com/", optOutUrl: "https://www.fastpeoplesearch.com/removal", removalMethod: "form", priorityTier: "high", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","email","relatives"]), notes: "May require CAPTCHA." },
  { name: "USPhoneBook", domain: "usphonebook.com", searchUrl: "https://www.usphonebook.com/", optOutUrl: "https://www.usphonebook.com/opt-out", removalMethod: "form", priorityTier: "high", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone"]) },
  { name: "TruePeopleSearch", domain: "truepeoplesearch.com", searchUrl: "https://www.truepeoplesearch.com/", optOutUrl: "https://www.truepeoplesearch.com/removal", removalMethod: "form", priorityTier: "high", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","email","relatives"]) },
  { name: "TruePeopleSearch.net", domain: "truepeoplesearch.net", searchUrl: "https://truepeoplesearch.net/search", optOutUrl: "https://truepeoplesearch.net/removal", removalMethod: "form", priorityTier: "high", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone"]) },
  { name: "ZoomInfo", domain: "zoominfo.com", searchUrl: "https://www.zoominfo.com/", optOutUrl: "https://www.zoominfo.com/about/privacy/privacy-center", removalMethod: "form", priorityTier: "high", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","email","phone","company","title"]), notes: "Primarily business data. Email verification required." },
  { name: "Equifax", domain: "equifax.com", searchUrl: "https://www.equifax.com/", optOutUrl: "https://www.equifax.com/personal/credit-report-services/", removalMethod: "phone", priorityTier: "high", difficultyRating: "hard", requiresId: false, requiresPhone: true, requiresPayment: false, dataTypes: JSON.stringify(["credit","financial","address","employment"]), notes: "Credit freeze: 1-800-349-9960." },
  { name: "Experian", domain: "experian.com", searchUrl: "https://www.experian.com/", optOutUrl: "https://www.experian.com/privacy/opting_out.html", removalMethod: "phone", priorityTier: "high", difficultyRating: "hard", requiresId: false, requiresPhone: true, requiresPayment: false, dataTypes: JSON.stringify(["credit","financial","address","employment"]), notes: "Credit freeze: 1-888-397-3742." },
  { name: "TransUnion", domain: "transunion.com", searchUrl: "https://www.transunion.com/", optOutUrl: "https://www.transunion.com/credit-freeze/place-credit-freeze", removalMethod: "phone", priorityTier: "high", difficultyRating: "hard", requiresId: false, requiresPhone: true, requiresPayment: false, dataTypes: JSON.stringify(["credit","financial","address","employment"]), notes: "Credit freeze: 1-888-909-8872." },
  { name: "LexisNexis", domain: "lexisnexis.com", searchUrl: "https://www.lexisnexis.com/", optOutUrl: "https://optout.lexisnexis.com/", removalMethod: "form", priorityTier: "high", difficultyRating: "hard", requiresId: true, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","criminal","financial","legal"]) },
  { name: "Thomson Reuters CLEAR", domain: "clear.thomsonreuters.com", searchUrl: "https://clear.thomsonreuters.com/", optOutUrl: "https://privacyportal.onetrust.com/webform/9228719e-b1c5-4b86-9c9e-b3b6e6e1c1e1/", removalMethod: "form", priorityTier: "high", difficultyRating: "hard", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","criminal","financial","legal"]) },

  // ─── STANDARD TIER ────────────────────────────────────────────────────────
  { name: "411.com", domain: "411.com", searchUrl: "https://www.411.com/", optOutUrl: "https://www.whitepages.com/suppression-requests", removalMethod: "phone", priorityTier: "standard", difficultyRating: "hard", requiresId: false, requiresPhone: true, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone"]), parentCompany: "WhitePages" },
  { name: "Archives.com", domain: "archives.com", searchUrl: "https://www.archives.com/", optOutUrl: "https://www.archives.com/optout", removalMethod: "account", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","historical"]), notes: "Requires free trial signup then cancel." },
  { name: "BackgroundCheckers", domain: "backgroundcheckers.net", searchUrl: "https://backgroundcheckers.net/", optOutUrl: "https://backgroundcheckers.net/optOut/", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","criminal"]) },
  { name: "Classmates.com", domain: "classmates.com", searchUrl: "https://www.classmates.com/", optOutUrl: "https://www.classmates.com/siteui/landing/cancelMembership", removalMethod: "account", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","school","location"]), parentCompany: "Intelius" },
  { name: "Cyber Background Checks", domain: "cyberbackgroundchecks.com", searchUrl: "https://www.cyberbackgroundchecks.com/", optOutUrl: "https://www.cyberbackgroundchecks.com/removal", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","criminal"]) },
  { name: "DOBSearch", domain: "dobsearch.com", searchUrl: "https://www.dobsearch.com/", optOutUrl: "https://www.dobsearch.com/people-finder/pf_optout.php", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","dob"]) },
  { name: "FaceCheck.id", domain: "facecheck.id", searchUrl: "https://facecheck.id/", optOutUrl: "https://facecheck.id/Face/Remove", removalMethod: "form", priorityTier: "standard", difficultyRating: "hard", requiresId: true, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["face","image"]), notes: "Requires face photo + blurred ID." },
  { name: "FamilySearch", domain: "familysearch.org", searchUrl: "https://www.familysearch.org/", optOutUrl: "https://www.familysearch.org/en/legal/privacy", removalMethod: "form", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","historical","family"]), notes: "Requires free account. Submit record URLs." },
  { name: "FreePeopleDirectory", domain: "freepeopledirectory.com", searchUrl: "https://www.freepeopledirectory.com/", optOutUrl: "https://www.spokeo.com/optout", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone"]), notes: "Uses Spokeo opt-out." },
  { name: "InfoTracer", domain: "infotracer.com", searchUrl: "https://infotracer.com/", optOutUrl: "https://infotracer.com/optout", removalMethod: "form", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","criminal"]) },
  { name: "InstantCheckmate", domain: "instantcheckmate.com", searchUrl: "https://www.instantcheckmate.com/", optOutUrl: "https://www.instantcheckmate.com/opt-out/", removalMethod: "form", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","criminal","relatives"]), parentCompany: "Intelius" },
  { name: "NeighborReport", domain: "neighborreport.com", searchUrl: "https://neighborreport.com/", optOutUrl: "https://neighborreport.com/optout/", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone"]) },
  { name: "NeighborWho", domain: "neighborwho.com", searchUrl: "https://www.neighborwho.com/", optOutUrl: "https://www.neighborwho.com/app/optout/search", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","relatives"]) },
  { name: "PeopleByName", domain: "peoplebyname.com", searchUrl: "https://www.peoplebyname.com/", optOutUrl: "https://www.peoplebyname.com/remove.php", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone"]) },
  { name: "PeopleFinders", domain: "peoplefinders.com", searchUrl: "https://www.peoplefinders.com/", optOutUrl: "https://www.peoplefinders.com/opt-out", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","criminal"]) },
  { name: "PeopleLooker", domain: "peoplelooker.com", searchUrl: "https://www.peoplelooker.com/", optOutUrl: "https://www.peoplelooker.com/f/optout/search", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","relatives"]), parentCompany: "Intelius" },
  { name: "PeopleSearchNow", domain: "peoplesearchnow.com", searchUrl: "https://www.peoplesearchnow.com/", optOutUrl: "https://www.peoplesearchnow.com/opt-out", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone"]) },
  { name: "PimEyes", domain: "pimeyes.com", searchUrl: "https://pimeyes.com/", optOutUrl: "https://pimeyes.com/en/optout", removalMethod: "form", priorityTier: "standard", difficultyRating: "hard", requiresId: true, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["face","image"]), notes: "Requires face photo + blurred ID upload." },
  { name: "PrivateEye", domain: "privateeye.com", searchUrl: "https://www.privateeye.com/", optOutUrl: "https://www.privateeye.com/static/view/optout/", removalMethod: "form", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","criminal"]) },
  { name: "PrivateRecords", domain: "privaterecords.net", searchUrl: "https://privaterecords.net/", optOutUrl: "https://privaterecords.net/optout", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone"]) },
  { name: "PropertyRecs", domain: "propertyrecs.com", searchUrl: "https://propertyrecs.com/", optOutUrl: "https://propertyrecs.com/opt-out", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","property"]) },
  { name: "Rehold", domain: "rehold.com", searchUrl: "https://rehold.com/", optOutUrl: "https://rehold.com/", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address"]) },
  { name: "SearchPeopleFree", domain: "searchpeoplefree.net", searchUrl: "https://www.searchpeoplefree.net/", optOutUrl: "https://www.searchpeoplefree.net/opt-out", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","email"]) },
  { name: "SearchQuarry", domain: "searchquarry.com", searchUrl: "https://www.searchquarry.com/", optOutUrl: "https://www.searchquarry.com/optout/", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","criminal"]) },
  { name: "Social Catfish", domain: "socialcatfish.com", searchUrl: "https://socialcatfish.com/", optOutUrl: "https://socialcatfish.com/opt-out/", removalMethod: "form", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","email","social"]) },
  { name: "SpyFly", domain: "spyfly.com", searchUrl: "https://www.spyfly.com/", optOutUrl: "https://www.spyfly.com/help-center/opt-out", removalMethod: "form", removalEmail: "support@spyfly.com", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: true, dataTypes: JSON.stringify(["name","address","phone","criminal"]) },
  { name: "TruthFinder", domain: "truthfinder.com", searchUrl: "https://www.truthfinder.com/", optOutUrl: "https://www.truthfinder.com/opt-out/", removalMethod: "form", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","criminal","relatives"]), parentCompany: "Intelius" },
  { name: "UnMask", domain: "unmask.com", searchUrl: "https://unmask.com/", optOutUrl: "https://unmask.com/opt-out/", removalMethod: "form", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone"]) },
  { name: "USA People Search", domain: "usapeoplesearch.com", searchUrl: "https://www.usapeoplesearch.com/", optOutUrl: "https://www.usapeoplesearch.com/optout.php", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone"]) },
  { name: "USA Official", domain: "usaofficial.com", searchUrl: "https://www.usaofficial.com/", optOutUrl: "https://www.usaofficial.com/privacy/optout", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone"]) },
  { name: "Veripages", domain: "veripages.com", searchUrl: "https://veripages.com/", optOutUrl: "https://veripages.com/page/optout", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","email"]) },
  { name: "VoterRecords", domain: "voterrecords.com", searchUrl: "https://voterrecords.com/", optOutUrl: "https://voterrecords.com/opt-out", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","voter","party"]) },
  { name: "US Search", domain: "ussearch.com", searchUrl: "https://www.ussearch.com/", optOutUrl: "https://www.ussearch.com/consumer/raf/landing.do", removalMethod: "form", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","criminal"]), parentCompany: "Intelius" },
  { name: "PeekYou", domain: "peekyou.com", searchUrl: "https://www.peekyou.com/", optOutUrl: "https://www.peekyou.com/about/contact/optout/", removalMethod: "form", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","social","address","phone"]) },
  { name: "Pipl", domain: "pipl.com", searchUrl: "https://pipl.com/", optOutUrl: "https://pipl.com/personal-information-removal-request/", removalMethod: "form", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","email","social","phone"]) },
  { name: "Ownerly", domain: "ownerly.com", searchUrl: "https://www.ownerly.com/", optOutUrl: "https://www.ownerly.com/opt-out", removalMethod: "form", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","property"]) },
  { name: "PublicRecords.com", domain: "publicrecords.com", searchUrl: "https://www.publicrecords.com/", optOutUrl: "https://www.publicrecords.com/optout", removalMethod: "form", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","criminal","court"]) },
  { name: "RecordsFinder", domain: "recordsfinder.com", searchUrl: "https://recordsfinder.com/", optOutUrl: "https://recordsfinder.com/opt-out/", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","criminal"]) },
  { name: "RocketReach", domain: "rocketreach.co", searchUrl: "https://rocketreach.co/", optOutUrl: "https://rocketreach.co/optout", removalMethod: "form", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","email","phone","company","title"]) },
  { name: "Apollo.io", domain: "apollo.io", searchUrl: "https://www.apollo.io/", optOutUrl: "https://www.apollo.io/privacy-policy#opt-out", removalMethod: "form", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","email","phone","company","title"]) },
  { name: "Lusha", domain: "lusha.com", searchUrl: "https://www.lusha.com/", optOutUrl: "https://www.lusha.com/privacy/opt-out/", removalMethod: "form", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","email","phone","company"]) },
  { name: "FullContact", domain: "fullcontact.com", searchUrl: "https://www.fullcontact.com/", optOutUrl: "https://www.fullcontact.com/privacy/opt-out/", removalMethod: "form", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","email","phone","social"]) },
  { name: "Epsilon", domain: "epsilon.com", searchUrl: "https://www.epsilon.com/", optOutUrl: "https://us.epsilon.com/privacy/optout", removalMethod: "form", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","demographics","purchase"]) },
  { name: "Melissa Data", domain: "melissadata.com", searchUrl: "https://www.melissa.com/", optOutUrl: "https://www.melissa.com/privacy", removalMethod: "form", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","demographics"]) },
  { name: "Dun & Bradstreet", domain: "dnb.com", searchUrl: "https://www.dnb.com/", optOutUrl: "https://www.dnb.com/utility-pages/privacy-policy.html#opt-out", removalMethod: "form", priorityTier: "standard", difficultyRating: "hard", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","company","address","financial"]) },
  { name: "Addresses.com", domain: "addresses.com", searchUrl: "https://www.addresses.com/", optOutUrl: "https://www.intelius.com/opt-out/", removalMethod: "form", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone"]), parentCompany: "Intelius" },
  { name: "Anywho", domain: "anywho.com", searchUrl: "https://www.anywho.com/", optOutUrl: "https://www.intelius.com/opt-out/", removalMethod: "form", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone"]), parentCompany: "Intelius" },
  { name: "Zabasearch", domain: "zabasearch.com", searchUrl: "https://www.zabasearch.com/", optOutUrl: "https://www.zabasearch.com/block_records/", removalMethod: "form", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone"]), parentCompany: "Intelius" },
  { name: "Searchbug", domain: "searchbug.com", searchUrl: "https://www.searchbug.com/", optOutUrl: "https://www.searchbug.com/info/optout.aspx", removalMethod: "form", priorityTier: "standard", difficultyRating: "hard", requiresId: false, requiresPhone: false, requiresPayment: true, dataTypes: JSON.stringify(["name","address","phone"]) },
  { name: "United States Phone Book", domain: "unitedstatesphonebook.com", searchUrl: "https://www.unitedstatesphonebook.com/", optOutUrl: "https://www.unitedstatesphonebook.com/opt_out.php", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone"]) },
  { name: "PeopleSmart", domain: "peoplesmart.com", searchUrl: "https://www.peoplesmart.com/", optOutUrl: "https://www.peoplesmart.com/opt-out-request", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","relatives"]), parentCompany: "Intelius" },
  { name: "411Locate", domain: "411locate.com", searchUrl: "https://www.411locate.com/", optOutUrl: "https://www.411locate.com/optout.php", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone"]) },
  { name: "PublicRecordsNow", domain: "publicrecordsnow.com", searchUrl: "https://www.publicrecordsnow.com/", optOutUrl: "https://www.publicrecordsnow.com/static/view/optout/", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","criminal"]) },
  { name: "BackgroundCheck.run", domain: "backgroundcheck.run", searchUrl: "https://backgroundcheck.run/", optOutUrl: "https://backgroundcheck.run/ng/control/privacy", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","criminal"]) },
  { name: "CourtCaseFinder", domain: "courtcasefinder.com", searchUrl: "https://courtcasefinder.com/", optOutUrl: "https://courtcasefinder.com/opt-out", removalMethod: "form", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","court","criminal"]) },
  { name: "Centeda", domain: "centeda.com", searchUrl: "https://centeda.com/", optOutUrl: "https://centeda.com/ng/control/privacy", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone"]) },
  { name: "ArrestFacts", domain: "arrestfacts.com", searchUrl: "https://arrestfacts.com/", optOutUrl: "https://arrestfacts.com/ng/control/privacy", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","arrest","criminal"]) },
  { name: "GovWarrantSearch", domain: "govwarrantsearch.org", searchUrl: "https://govwarrantsearch.org/", optOutUrl: "https://govwarrantsearch.org/opt-out", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","warrant","criminal"]) },
  { name: "CheckSecrets", domain: "checksecrets.com", searchUrl: "https://checksecrets.com/", optOutUrl: "https://checksecrets.com/opt-out", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","criminal"]) },
  { name: "FindPeopleSearch", domain: "findpeoplesearch.com", searchUrl: "https://findpeoplesearch.com/", optOutUrl: "https://findpeoplesearch.com/customerservice", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone"]) },
  { name: "InmateSearcher", domain: "inmatesearcher.com", searchUrl: "https://inmatesearcher.com/", optOutUrl: "https://inmatesearcher.com/opt-out", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","criminal","inmate"]) },
  { name: "Idstrong", domain: "idstrong.com", searchUrl: "https://www.idstrong.com/", optOutUrl: "https://www.idstrong.com/optout/", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","criminal"]) },
  { name: "NumberGuru", domain: "numberguru.com", searchUrl: "https://www.numberguru.com/", optOutUrl: "https://www.numberguru.com/optout", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["phone","name","address"]) },
  { name: "QuickPeopleTrace", domain: "quickpeopletrace.com", searchUrl: "https://www.quickpeopletrace.com/", optOutUrl: "https://www.quickpeopletrace.com/optout.php", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone"]) },
  { name: "Veriforia", domain: "veriforia.com", searchUrl: "https://veriforia.com/", optOutUrl: "https://veriforia.com/opt-out/", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone"]) },
  { name: "Clubset", domain: "clubset.com", searchUrl: "https://clubset.com/", optOutUrl: "https://clubset.com/profile/remove", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone"]) },
  { name: "FindRec", domain: "findrec.com", searchUrl: "https://findrec.com/", optOutUrl: "https://findrec.com/opt-out", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","criminal"]) },
  { name: "USWarrants", domain: "uswarrants.com", searchUrl: "https://www.uswarrants.com/", optOutUrl: "https://www.uswarrants.com/opt-out", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","warrant","criminal"]) },
  { name: "AffordableBackgroundChecks", domain: "affordablebackgroundchecks.com", searchUrl: "https://www.affordablebackgroundchecks.com/", optOutUrl: "https://www.affordablebackgroundchecks.com/opt_out.php", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","criminal"]) },
  { name: "Open Public Records", domain: "open-public-records.com", searchUrl: "https://open-public-records.com/", optOutUrl: "https://open-public-records.com/opt-out", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","criminal"]) },
  { name: "PrivateReports", domain: "privatereports.com", searchUrl: "https://privatereports.com/", optOutUrl: "https://privatereports.com/opt-out", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone"]) },
  { name: "ReversePhoneCheck", domain: "reversephonecheck.com", searchUrl: "https://www.reversephonecheck.com/", optOutUrl: "https://www.reversephonecheck.com/opt-out/", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["phone","name","address"]) },
  { name: "SecretInfo", domain: "secretinfo.com", searchUrl: "https://secretinfo.com/", optOutUrl: "https://secretinfo.com/optout/", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone"]) },
  { name: "USATrace", domain: "usatrace.com", searchUrl: "https://www.usatrace.com/", optOutUrl: "https://www.usatrace.com/opt-out", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone"]) },
  { name: "PublicSearcher", domain: "publicsearcher.com", searchUrl: "https://publicsearcher.com/", optOutUrl: "https://publicsearcher.com/opt-out", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone"]) },
  { name: "SealedRecords", domain: "sealedrecords.net", searchUrl: "https://sealedrecords.net/", optOutUrl: "https://sealedrecords.net/opt-out", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","criminal","court"]) },
  { name: "TruthRecord", domain: "truthrecord.org", searchUrl: "https://www.truthrecord.org/", optOutUrl: "https://www.truthrecord.org/opt-out", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","criminal"]) },
  { name: "Dataveria", domain: "dataveria.com", searchUrl: "https://dataveria.com/", optOutUrl: "https://dataveria.com/profile/control", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone"]) },
  { name: "EmailTracer", domain: "emailtracer.com", searchUrl: "https://www.emailtracer.com/", optOutUrl: "https://www.emailtracer.com/opt-out/", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["email","name","address"]) },
  { name: "FastBackgroundCheck", domain: "fastbackgroundcheck.com", searchUrl: "https://www.fastbackgroundcheck.com/", optOutUrl: "https://www.fastbackgroundcheck.com/removal", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","criminal"]) },
  { name: "CallerSmart", domain: "callersmart.com", searchUrl: "https://www.callersmart.com/", optOutUrl: "https://www.callersmart.com/opt-out", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["phone","name"]) },
  { name: "Selfie Network", domain: "selfienetwork.com", searchUrl: "https://selfienetwork.com/", optOutUrl: "https://selfienetwork.com/optout/", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone"]) },
  { name: "PeopleSearchUSA", domain: "peoplesearchusa.org", searchUrl: "https://www.peoplesearchusa.org/", optOutUrl: "https://www.peoplesearchusa.org/opt-out", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone"]) },
  { name: "PersonSearchers", domain: "personsearchers.com", searchUrl: "https://personsearchers.com/", optOutUrl: "https://personsearchers.com/optout/", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone"]) },
  { name: "PeopleWin", domain: "peoplewin.com", searchUrl: "https://www.peoplewin.com/", optOutUrl: "https://www.peoplewin.com/opt-out", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone"]) },
  { name: "OpenPublicRecords", domain: "openpublicrecords.com", searchUrl: "https://openpublicrecords.com/", optOutUrl: "https://openpublicrecords.com/opt-out", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","criminal"]) },
  { name: "SocialSearcher", domain: "social-searcher.com", searchUrl: "https://www.social-searcher.com/", optOutUrl: "https://www.social-searcher.com/privacy-policy/", removalMethod: "email", removalEmail: "support@social-searcher.com", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","social","posts"]) },
  { name: "Gravy Analytics", domain: "gravyanalytics.com", searchUrl: "https://gravyanalytics.com/", optOutUrl: "https://gravyanalytics.com/privacy/", removalMethod: "form", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["location","demographics"]) },
  { name: "AnalyticsIQ", domain: "analyticsiq.com", searchUrl: "https://analyticsiq.com/", optOutUrl: "https://analyticsiq.com/privacy-policy/", removalMethod: "form", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["demographics","purchase","financial"]) },
  { name: "Foursquare", domain: "foursquare.com", searchUrl: "https://foursquare.com/", optOutUrl: "https://privacy.foursquare.com/", removalMethod: "form", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["location","name","social"]) },
  { name: "Mobilewalla", domain: "mobilewalla.com", searchUrl: "https://mobilewalla.com/", optOutUrl: "https://mobilewalla.com/privacy-policy", removalMethod: "form", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["location","demographics","mobile"]) },
  { name: "Aristotle", domain: "aristotle.com", searchUrl: "https://aristotle.com/", optOutUrl: "https://aristotle.com/privacy/", removalMethod: "form", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["voter","name","address","political"]) },
  { name: "Lead411", domain: "lead411.com", searchUrl: "https://www.lead411.com/", optOutUrl: "https://www.lead411.com/opt-out.html", removalMethod: "form", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","email","phone","company","title"]) },
  { name: "Inforver", domain: "inforver.com", searchUrl: "https://inforver.com/", optOutUrl: "https://inforver.com/opt-out", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone"]) },
  { name: "NewEnglandFacts", domain: "newenglandfacts.com", searchUrl: "https://newenglandfacts.com/", optOutUrl: "https://newenglandfacts.com/ng/control/privacy", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone"]) },
  { name: "TexasArrests", domain: "texasarrests.org", searchUrl: "https://texasarrests.org/", optOutUrl: "https://texasarrests.org/opt-out", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","arrest","criminal"]) },
  { name: "MugshotLook", domain: "mugshotlook.com", searchUrl: "https://mugshotlook.com/", optOutUrl: "https://mugshotlook.com/opt-out", removalMethod: "form", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","mugshot","arrest"]) },
  { name: "Councilon", domain: "councilon.com", searchUrl: "https://councilon.com/", optOutUrl: "https://councilon.com/ex/control/privacy", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone"]) },
  { name: "BackgroundChecks.me", domain: "backgroundchecks.me", searchUrl: "https://backgroundchecks.me/", optOutUrl: "https://backgroundchecks.me/opt-out", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","criminal"]) },
  { name: "BackgroundChecks.org", domain: "backgroundchecks.org", searchUrl: "https://backgroundchecks.org/", optOutUrl: "https://backgroundchecks.org/justdeleteme/", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","criminal"]) },
  { name: "Government Registry", domain: "governmentregistry.org", searchUrl: "https://governmentregistry.org/", optOutUrl: "https://governmentregistry.org/ng/control/privacy", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","voter"]) },
  { name: "SearchSystems", domain: "searchsystems.net", searchUrl: "https://searchsystems.net/", optOutUrl: "https://searchsystems.net/privacy.php", removalMethod: "email", removalEmail: "privacy@searchsystems.net", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","court","criminal"]) },
  { name: "PeopleSearch123", domain: "peoplesearch123.com", searchUrl: "https://www.peoplesearch123.com/", optOutUrl: "https://www.peoplesearch123.com/optout", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone"]) },
  { name: "PeopleSearcher", domain: "peoplesearcher.com", searchUrl: "https://www.peoplesearcher.com/", optOutUrl: "https://www.peoplesearcher.com/opt-out", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone"]) },
  { name: "CallerID Test", domain: "calleridtest.com", searchUrl: "https://www.calleridtest.com/", optOutUrl: "https://www.calleridtest.com/opt-out", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["phone","name"]) },
  { name: "Spokeo (UK)", domain: "spokeo.co.uk", searchUrl: "https://www.spokeo.co.uk/", optOutUrl: "https://www.spokeo.com/optout", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone"]) },
  { name: "Yellowbook", domain: "yellowbook.com", searchUrl: "https://www.yellowbook.com/", optOutUrl: "https://www.yellowbook.com/privacy-policy", removalMethod: "form", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","business"]) },
  { name: "Innovis", domain: "innovis.com", searchUrl: "https://www.innovis.com/", optOutUrl: "https://www.innovis.com/securityFreeze/index", removalMethod: "phone", priorityTier: "standard", difficultyRating: "hard", requiresId: false, requiresPhone: true, requiresPayment: false, dataTypes: JSON.stringify(["credit","financial","address"]), notes: "Credit freeze: 1-800-540-2505." },
  { name: "ChexSystems", domain: "chexsystems.com", searchUrl: "https://www.chexsystems.com/", optOutUrl: "https://www.chexsystems.com/security-freeze/place-freeze", removalMethod: "phone", priorityTier: "standard", difficultyRating: "hard", requiresId: false, requiresPhone: true, requiresPayment: false, dataTypes: JSON.stringify(["banking","financial","address"]), notes: "Banking freeze: 1-800-428-9623." },
  { name: "Datazapp", domain: "datazapp.com", searchUrl: "https://datazapp.com/", optOutUrl: "https://datazapp.com/opt-out", removalMethod: "form", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","demographics"]) },
  { name: "Spokeo People Search", domain: "people.spokeo.com", searchUrl: "https://people.spokeo.com/", optOutUrl: "https://www.spokeo.com/optout", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","email"]), parentCompany: "Spokeo" },
  { name: "SelfieNetwork", domain: "selfienetwork.net", searchUrl: "https://selfienetwork.net/", optOutUrl: "https://selfienetwork.net/optout/", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone"]) },
  { name: "PrivacyStar", domain: "privacystar.com", searchUrl: "https://www.privacystar.com/", optOutUrl: "https://www.privacystar.com/privacy-policy", removalMethod: "email", removalEmail: "privacy@privacystar.com", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["phone","name","address"]) },
  { name: "Pipl (API)", domain: "pipl.com/api", searchUrl: "https://pipl.com/", optOutUrl: "https://pipl.com/personal-information-removal-request/", removalMethod: "form", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","email","phone","social","address"]) },
  { name: "Spokeo Business", domain: "business.spokeo.com", searchUrl: "https://business.spokeo.com/", optOutUrl: "https://www.spokeo.com/optout", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","email"]), parentCompany: "Spokeo" },
  { name: "Haines & Company", domain: "haines.ca", searchUrl: "https://www.haines.ca/", optOutUrl: "https://www.haines.ca/privacy", removalMethod: "email", removalEmail: "privacy@haines.ca", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone"]) },
  { name: "Enformion", domain: "enformion.com", searchUrl: "https://enformion.com/", optOutUrl: "https://enformion.com/privacy/", removalMethod: "form", priorityTier: "standard", difficultyRating: "hard", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","criminal"]), notes: "Formerly Endato. Many sites use their API." },
  { name: "Endato", domain: "endato.com", searchUrl: "https://endato.com/", optOutUrl: "https://endato.com/privacy", removalMethod: "form", priorityTier: "standard", difficultyRating: "hard", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","phone","criminal"]) },
  { name: "Cuebiq", domain: "cuebiq.com", searchUrl: "https://cuebiq.com/", optOutUrl: "https://cuebiq.com/optout/", removalMethod: "form", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["location","demographics","mobile"]) },
  { name: "KnowThyCustomer", domain: "knowthycustomer.com", searchUrl: "https://knowthycustomer.com/", optOutUrl: "https://knowthycustomer.com/privacy", removalMethod: "form", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","financial","demographics"]) },
  { name: "Merkle", domain: "merkleinc.com", searchUrl: "https://www.merkleinc.com/", optOutUrl: "https://www.merkleinc.com/privacy/privacy-notice", removalMethod: "form", priorityTier: "standard", difficultyRating: "medium", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["name","address","demographics","purchase"]) },
  { name: "Spokeo Reverse Phone", domain: "reverse.spokeo.com", searchUrl: "https://reverse.spokeo.com/", optOutUrl: "https://www.spokeo.com/optout", removalMethod: "form", priorityTier: "standard", difficultyRating: "easy", requiresId: false, requiresPhone: false, requiresPayment: false, dataTypes: JSON.stringify(["phone","name","address"]), parentCompany: "Spokeo" },
];

// Insert in batches of 20
const batchSize = 20;
let inserted = 0;
for (let i = 0; i < brokers.length; i += batchSize) {
  const batch = brokers.slice(i, i + batchSize);
  const values = batch.map(b => `(
    ${JSON.stringify(b.name)},
    ${JSON.stringify(b.domain)},
    ${b.searchUrl ? JSON.stringify(b.searchUrl) : 'NULL'},
    ${b.optOutUrl ? JSON.stringify(b.optOutUrl) : 'NULL'},
    ${JSON.stringify(b.removalMethod)},
    ${b.removalEmail ? JSON.stringify(b.removalEmail) : 'NULL'},
    ${JSON.stringify(b.priorityTier)},
    ${JSON.stringify(b.difficultyRating)},
    ${b.requiresId ? 1 : 0},
    ${b.requiresPhone ? 1 : 0},
    ${b.requiresPayment ? 1 : 0},
    ${b.dataTypes ? `JSON_ARRAY(${JSON.parse(b.dataTypes).map(d => JSON.stringify(d)).join(',')})` : 'NULL'},
    ${b.parentCompany ? JSON.stringify(b.parentCompany) : 'NULL'},
    ${b.subsidiaries ? `JSON_ARRAY(${JSON.parse(b.subsidiaries).map(s => JSON.stringify(s)).join(',')})` : 'NULL'},
    ${b.notes ? JSON.stringify(b.notes) : 'NULL'},
    1
  )`).join(',\n');

  await connection.execute(`
    INSERT IGNORE INTO data_brokers 
    (name, domain, searchUrl, optOutUrl, removalMethod, removalEmail, priorityTier, difficultyRating, requiresId, requiresPhone, requiresPayment, dataTypes, parentCompany, subsidiaries, notes, isActive)
    VALUES ${values}
  `);
  inserted += batch.length;
  console.log(`Inserted ${inserted}/${brokers.length} brokers`);
}

// Seed subscription plans
await connection.execute(`
  INSERT IGNORE INTO subscription_plans (name, slug, maxMembers, priceMonthly, priceAnnual, features, isActive)
  VALUES 
  ('Individual', 'individual', 1, 9.99, 99.99, JSON_ARRAY(
    'Scan 150+ data broker sites',
    'Automated removal requests',
    'Weekly re-scan monitoring',
    'Breach Alerts (HIBP)',
    'Privacy score dashboard',
    'LLM-powered opt-out assistance',
    'Google & Bing deindex tracking',
    '1 identity profile'
  ), 1),
  ('Family', 'family', 5, 19.99, 199.99, JSON_ARRAY(
    'Everything in Individual',
    'Up to 5 family members',
    'Family privacy score overview',
    'Shared breach alert dashboard',
    'Priority removal processing',
    'Monthly detailed reports',
    'Dedicated support'
  ), 1),
  ('Organization', 'organization', 25, 49.99, 499.99, JSON_ARRAY(
    'Everything in Family',
    'Up to 25 members',
    'Organization-wide privacy dashboard',
    'Bulk identity scanning',
    'Custom removal workflows',
    'API access',
    'Compliance reporting (GDPR/CCPA)',
    'Dedicated account manager',
    'SLA guarantee'
  ), 1)
`);
console.log("Subscription plans seeded");

await connection.end();
console.log(`\nDone! Seeded ${brokers.length} data brokers and 3 subscription plans.`);
